### ISSUE TITLE
Update to Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters-ansible#22]
It'll be released on 2018-04-26 and it'd be nice to update Lobsters to move up to [Ruby 2.5.1](https://packages.ubuntu.com/search?keywords=ruby&searchon=names&suite=bionic&section=all).

Because this is a big update, we should use the `lobsters-test` staging server to confirm the playbook can configure and start Lobsters from scratch. Our current install included some hand config, so we can build confidence that all of that config has been encoded into ansible properly.

**Comment by jstoja** [comment]
I was thinking that this could be easily tested with Vagrant + the `lobsters-test` server.
Have you any idea about the issues that there could be with the Rails app and Ruby 2.5.1?

It would be very cool to test the `lobsters-ansible` repo from the ground up to setup the test server so we could test that it's actually correctly provisioning everything (that would be a good disaster recovery starting point). What do you think about it?

Btw, I was thinking, is there any requirements to keep the `yum`packages management stuff in the roles? It won't be tested so often and I think it's exactly like postgres, it's possible to use it, but as long as we don't actively support it, it probably shouldn't be part of this. What's your ideas about this?

**Comment by alanpost** [comment]
@jstoja The yum stuff is vestigial and unused--I've been considering a RedHat/CentOS test system as a means of ensuring the lobsters codebase can be deployed on that platform, but I'm not aware of any actual demand for that.  If we want the playbook to be Ubuntu-only it certainly would simplify it.  Anyone else away of any users / demand for that platform?

**Comment by alanpost** [comment]
Just before our maintenance window we'd been working on an Ubuntu 18 image.  We've got a couple SSH-related regressions to fix before we can release it.  We'll pick it back up next week and I'll be in a better position to estimate when they'll be available.

**Comment by jstoja** [comment]
Thank you so much @alanpost for all these updates, and thanks again to you and all the prgmr crew for the maintenances and all the work!

For the user demand, I guess the simplest way to do it is just to add a note about it in the README and work from that. I'll wait for Peter's answer to make a PR about this if he agrees :)

**Comment by pushcx** [comment]
> We'll pick it back up next week

Yeah, let's try not to make two high-risk changes in the same week. :)

And definitely not three - I updated our bundle for a security release and we could update to Rails 5.2. That'll keep, too.

**Comment by pushcx** [comment]
@alynpost I installed `update-manager-core` and saw:

```
# do-release-upgrade -c
Checking for a new Ubuntu release
New release '18.04.2 LTS' available.
Run 'do-release-upgrade' to upgrade to it.
```

Let's find some time to run this on staging soonish, now that 2.3 is EOL'd...

**Comment by pushcx** [comment]
Reopening - we've got Ruby 2.5 on test, but I'd like to track that this is not completed on prod.

**Comment by thomasdziedzic** [comment]
Bump, this is still blocking my rails 6 pr.

**Comment by pushcx** [comment]
We're on 20.04 in prod now.
