### ISSUE TITLE
Automate manual deploy steps

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters-ansible#3]
- [x] precompile assets
 - [x] run `rails db:migrate`
 - [x] bounce Unicorn, which doesn't seem to be reloading code on HUP like [the docs say](https://bogomips.org/unicorn/SIGNALS.html). This bounce almost certainly needs to go into the `logrotate` config as well.

**Comment by pushcx** [comment]
Yeah, just tested `kill -HUP` with unicorn's pid. It reloads the views but not the app code, which I think is what led to https://github.com/lobsters/lobsters/issues/418

**Comment by jstoja** [comment]
[Like docs say](https://bogomips.org/unicorn/SIGNALS.html):
With:
> HUP - reloads config file and gracefully restart all workers. [...] If "preload_app" is true, then application code changes will have no effect; USR2 + QUIT (see below) must be used to load newer code in this case. [...]

with:
> * QUIT - graceful shutdown, waits for workers to finish their current request before finishing.
> * USR2 - reexecute the running binary. A separate QUIT should be sent to the original process once the child is verified to be up and running.

I guess that answers the bounce.

**Comment by pushcx** [comment]
The config file does not have `preload_app` set and it defaults to false, so it's still a puzzle as to why `HUP` isn't working.

**Comment by pushcx** [comment]
I've triple-checked that the doc for unicorn symbols is current and what we're running in prod because it continues to surprise me. I just sent unicorn `USR2` and it loaded new code, but the previous process exited without me needing to send it `QUIT`. I think we should still send the signal, but I don't know that it's needed.
