### ISSUE TITLE
Cert renewal must bounce nginx

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters-ansible#42]
I noticed our cert was due to expire. @alanpost diagnosed that the cert had correctly renewed but we needed to restart nginx for it to replace the old one.

We need cert renewal to signal/restart nginx to promptly start using the new cert.

**Comment by Tenzer** [comment]
I believe using the [Nginx plugin](https://certbot.eff.org/docs/using.html#nginx) for Certbot should solve this, alternatively [manual hooks](https://certbot.eff.org/docs/using.html#renewing-certificates) can be specified to be run before and after the certificate renewals.

The Let's Encrypt installation and configuration doesn't seem to be part of this repository, so not really possible to contribute to.

**Comment by pushcx** [comment]
The `certbot` ansible module I added now handles this correctly.
