### ISSUE TITLE
Install ruby2.5 package on lobsters.

### ISSUE THREAD

**Issue by thomasdziedzic** [lobsters/lobsters-ansible#46]
Now that ubuntu has been upgraded to 18.04, we should install ruby 2.5 so we can complete the upgrade. https://github.com/lobsters/lobsters-ansible/pull/44#discussion_r324225211

This is blocking the ruby 2.5.1 upgrade for lobsters https://github.com/lobsters/lobsters/pull/573 and the rails 6.0 upgrade https://github.com/lobsters/lobsters/pull/723

**Comment by pushcx** [comment]
Caveat: prod is still 16.04; only test is 18.04 atm.

**Comment by thomasdziedzic** [comment]
Closing since prod is on 2.7.0 now.
