### ISSUE TITLE
import nginx conf

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters-ansible#5]
This was manually configured on prod based on the previous hosting and should be recorded in the playbook.

**Comment by jstoja** [comment]
hey @pushcx any update on the configurations? Since the concern was the secrets that it could contain, I think nginx unicorn configs should be empty of these, and it could be a start. What do you think?

**Comment by pushcx** [comment]
Reviewied and committed in 86c3b903fe7511888b23ae1bbe9902d9aa6d2d7f, though I didn't write a task to install the files (or mariadb's my.cnf, now that I look at it).

**Comment by pushcx** [comment]
Done in 9f0691b].
