### ISSUE TITLE
Add rate-limited to the peterson sopel trigger.

### ISSUE THREAD

**Issue by alanpost** [lobsters/lobsters-ansible#51]
We have a trigger in #lobsters such that if a user names Jordon Peterson (via [Pp]eterson) we issue our standard blurb regarding non-association despite both communities using the label "Lobsters:"

13:05 <alynpost> peterson
13:05 <mockturtle> alynpost: The site has nothing to do with Jordan Peterson: https://lobste.rs/about#michaelbolton

This trigger is implemented in the following sopel module:

https://github.com/lobsters/lobsters-ansible/blob/master/roles/mockturtle/files/sopel_modules/peterson.py

The problem is that it triggers every time a user matches the trigger.  It would be better if the trigger had a rate limit so it only replied every 5 minutes.  The sopel API has a rate limiter, which can be used for this trigger to do just that:

https://sopel.chat/docs/plugin.html#sopel.module.rate

This issue covers adding that rate limiter as a decorator in the peterson module.

**Comment by bbuccianti** [comment]
Great explanation!

I think this commit resolves this issue https://github.com/bbuccianti/lobsters-ansible/commit/34999617b71eca1b8e514a3f13d6a186443b663b

**Comment by bbuccianti** [comment]
Maybe that was wrong. It's limiting on a per-user basis we want on channel.

Isn't this https://github.com/bbuccianti/lobsters-ansible/commit/16cd976fb41fc0db53a097aa3037cab1c2075a08 better?

**Comment by alanpost** [comment]
Fixed in PR #52.
