### ISSUE TITLE
add sopel module to get repo notifications through irc

### ISSUE THREAD

**Issue by bbuccianti** [lobsters/lobsters-ansible#54]
We were discussing on irc (#lobsters channel or #lobsters-dev ?)about adding this kind of notifications. Sopel has a module available but it needs testing in order to get it to work.

Also would be necessary to provide it with tokens as you can see in the repo of the module https://github.com/sopel-irc/sopel-github

**Comment by pushcx** [comment]
We stopped running the [sopel-based bot](https://github.com/lobsters/mockturtle-v1) a few years ago. I've opened a PR over on the current bot to handle this.
