### ISSUE TITLE
import unicorn conf

### ISSUE THREAD

**Issue by pushcx** [lobsters/lobsters-ansible#6]
This was manually configured on prod based on the previous hosting and should be recorded in the playbook.

**Comment by jstoja** [comment]
This could potentially be part of the service configuration with #7 .

**Comment by jstoja** [comment]
Can you copy paste the configs on each PR for what's on prod for unicorn/nginx/mysql so we can integrate them? That'll be a starting point for making sure that the playbook reflects the production.
