### ISSUE TITLE
Tarsnap packaging key is expired

### ISSUE THREAD

**Issue by shanemhansen** [lobsters/lobsters-ansible#65]
The current key, located at https://github.com/lobsters/lobsters-ansible/blob/cb938831c4025213ccd58f7152c32e110c9e81f2/roles/tarsnap/files/tarsnap-deb-packaging-key.asc

Is expired. Running gpg on it shows:

```
pub   rsa4096 2017-02-04 [SC] [expired: 2018-02-01]
      28506A18C3F0BA4C870FC74940B98B68F04DE775
uid           Tarsnap .deb packages signing key (Tarsnap Backup Inc.) <pkg-deb@tarsnap.com>
```

**Comment by pushcx** [comment]
Thanks for spotting this. I rolled this into `21cc540`.
