### ISSUE TITLE
Ruby version with Ubuntu Bionic

### ISSUE THREAD

**Issue by jstoja** [lobsters/lobsters-ansible#68]
Hello,

I'm trying to fix the Vagrant scripts and from what I can see from past issues, the last state of the server is with Ubuntu Bionic (18.04 LTS). That being said, the `lobsters` role is installing `ruby2.7` that is available only for more recent versions: https://packages.ubuntu.com/bionic/ruby

Could someone mention which version is deployed? I think that this kind of information would be nice for sister sites to know which version they should install to have those scripts working.

Best,
J

**Comment by pushcx** [comment]
We're now running on Ubuntu 20.04 with Ruby 2.7:

```
# ruby --version
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
```
